spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  profiles:
    include:
      - rds
    active: local

logging:
  level:
    org.hibernate.type: trace

spring.batch.job.names: ${job.name:NONE}