version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DB=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
